version: "3.8"

services:
    php:
        container_name: php
        build:
            context: server/php
            args:
                GIT_NAME: '${GIT_NAME}'
                GIT_EMAIL: '${GIT_EMAIL}'
                UID: '${UID:-1000}'
                GID: '${GID:-1000}'
        ports:
            - '9003:9003'
        volumes:
            - ./:/var/www
            - ./server/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./compose.yaml:/var/www/compose.yaml:rw
        environment:
            SYMFONY_VERSION: '${SYMFONY_VERSION:-7.0.*}'
        networks:
            - private
        extra_hosts:
            - host.docker.internal:host-gateway

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '80:80'
        volumes:
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./server/nginx/fastcgi_params:/etc/nginx/fastcgi_params
        depends_on:
            - php
        networks:
            - public
            - private

    swagger:
        image: swaggerapi/swagger-ui
        container_name: swagger
        ports:
            - '81:8080'
        volumes:
            - ./server/swagger:/usr/share/nginx/html/resources
        environment:
            API_URL: resources/api.yaml
        networks:
            - public

networks:
    public:
        driver: bridge
    private:
